/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertCircle: typeof import('lucide-vue-next')['AlertCircle']
    AnnouncementManager: typeof import('./components/overlay-controller/AnnouncementManager.vue')['default']
    AnnouncementTicker: typeof import('./components/overlay/AnnouncementTicker.vue')['default']
    BackButton: typeof import('./components/BackButton.vue')['default']
    ContestClock: typeof import('./components/overlay/ContestClock.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    FilterButtonGroup: typeof import('./components/FilterButtonGroup.vue')['default']
    GlobalConfigPanel: typeof import('./components/overlay-controller/GlobalConfigPanel.vue')['default']
    InfoCard: typeof import('./components/InfoCard.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    LogOut: typeof import('lucide-vue-next')['LogOut']
    MetricBar: typeof import('./components/MetricBar.vue')['default']
    MissionModal: typeof import('./components/MissionModal.vue')['default']
    MissionSelect: typeof import('./components/MissionSelect.vue')['default']
    MissionTable: typeof import('./components/MissionTable.vue')['default']
    MultiContestantPanel: typeof import('./components/overlay-controller/MultiContestantPanel.vue')['default']
    MultiContestantView: typeof import('./components/overlay/MultiContestantView.vue')['default']
    OverlayFooter: typeof import('./components/overlay/OverlayFooter.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RankingConfigPanel: typeof import('./components/overlay-controller/RankingConfigPanel.vue')['default']
    RankingDisplay: typeof import('./components/overlay/RankingDisplay.vue')['default']
    RankingView: typeof import('./components/overlay/RankingView.vue')['default']
    RefreshButton: typeof import('./components/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    SingleContestantPanel: typeof import('./components/overlay-controller/SingleContestantPanel.vue')['default']
    SingleContestantView: typeof import('./components/overlay/SingleContestantView.vue')['default']
    StatCounter: typeof import('./components/StatCounter.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    SubmissionQueue: typeof import('./components/overlay/SubmissionQueue.vue')['default']
    TeamInfoFloat: typeof import('./components/overlay/TeamInfoFloat.vue')['default']
    ToggleButton: typeof import('./components/ToggleButton.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
  }
}
