/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBackButton: typeof import('./components/AppBackButton.vue')['default']
    AppDashboardCard: typeof import('./components/AppDashboardCard.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/UserForm.vue')['default']
  }
}
